#!/bin/bash
#
# Test the Varnish S2I image in OpenShift (local cluster)
#
# IMAGE_NAME specifies a name of the candidate image used for testing.
# The image has to be available before this script is executed.
# VERSION specifies the major version of the Varnish runtime in format of X.Y
# OS specifies RHEL version (e.g. OS=rhel7)
#

THISDIR=$(dirname ${BASH_SOURCE[0]})

source ${THISDIR}/test-lib-varnish.sh

set -eo nounset

trap ct_os_cleanup EXIT SIGINT

ct_os_check_compulsory_vars

ct_os_cluster_up

# test with the just built image and an integrated template
test_varnish_integration "${IMAGE_NAME}"

# test with a released image and an integrated template
if [ "${OS}" == "rhel7" ] ; then
  PUBLIC_IMAGE_NAME=${PUBLIC_IMAGE_NAME:-${REGISTRY:-registry.redhat.io/}rhscl/${BASE_IMAGE_NAME}-${VERSION//./}-rhel7}
else
  PUBLIC_IMAGE_NAME=${PUBLIC_IMAGE_NAME:-${REGISTRY:-}centos/${BASE_IMAGE_NAME}-${VERSION//./}-centos7}
fi

export CT_SKIP_UPLOAD_IMAGE=true
test_varnish_integration "${PUBLIC_IMAGE_NAME}"

# Check the imagestream
test_varnish_imagestream

OS_TESTSUITE_RESULT=0

ct_os_cluster_down

